Add new --help and --version options.

diff --git a/src/Infrastructure/stubs/mpiuni/mpirun b/src/Infrastructure/stubs/mpiuni/mpirun
--- a/src/Infrastructure/stubs/mpiuni/mpirun
+++ b/src/Infrastructure/stubs/mpiuni/mpirun
@@ -1,22 +1,42 @@
 #!/bin/sh
-# $Id: mpirun,v 1.1 2004/06/04 15:48:02 nscollins Exp $
-if [ $1 !=  "-np" ]; then
-progname=$*
-elif  [ $2 =  "1" ]; then
-shift ; shift
-progname=$*
-else
-echo "FAIL:Uniprocessor version of MPI can only use one processor."
-exit 1
-fi
+# $Id: mpirun,v 1.2 2012/01/18 20:22:46 w6ws Exp $
 
+CYCLE=1
+while [ $CYCLE = 1 ]
+do
+    case $1 in
+    --help)
+	echo "Usage: mpirun [OPTION]... [command [arg ...]]"
+	echo "-np 1       run the command with one processor (default)"
+	echo "--help      display this help and exit"
+	echo "--version   output version information and exit"
+	exit 0
+	;;
+
+    -np)
+	if [ $2 != "1" ]; then
+	    echo "FAIL:Uniprocessor version of MPI can only use one processor."
+	    exit 1
+	fi
+	shift; shift
+	;;
+
+    --version)
+	echo "ESMF mpiuni: $Revision: 1.2 $ $Date: 2012/01/18 20:22:46 $ $Name:  $"
+	exit 0
+	;;
+
+    *)
+	CYCLE=0;;
+    esac
+done
+
+if [ $1 != "" ]; then
 # If relative path is used prepend a ./
-tail=`echo $progname | sed 's/\/.*//'` 
-if  [ "$tail" != "" ]; then
-  progname="./$progname"
-fi
+    progname=`dirname $1`/`basename $1`
+    echo progname = $progname
+    shift
 
 # Execute the program
-$progname
-exit 0
-
+    $progname $*
+fi
