test install

diff --git a/.github/workflows/test-build-spack.yaml b/.github/workflows/test-build-spack.yaml
--- a/.github/workflows/test-build-spack.yaml
+++ b/.github/workflows/test-build-spack.yaml
@@ -83,3 +83,11 @@ jobs:
         ${{ github.workspace }}/.github/workflows/scripts/run_nuopc_app_proto.sh \
           -r ${{ github.workspace }}/nuopc-app-prototypes \
           -s ~/.spack-ci
+        lineFrom=`cat -n testProtos.log | grep "== TEST SUMMARY START ==" | awk '{print $1}'`
+        lineTo=`cat -n testProtos.log | grep "== TEST SUMMARY STOP ==" | awk '{print $1}'`
+        result=`sed -n '${lineFrom},${lineTo}p' testProtos.log | grep "FAIL"`
+        if [[ ! -z "$result" ]]; then
+          echo "Failed NUOPC app prototypes ..."
+          echo $result
+          exit 1
+        fi
